# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likesbooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='liked_users',
            new_name='liked_by',
        ),
    ]
